apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-foundation
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/refresh: "hard"
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-service-app: "true"
  template:
    metadata:
      name: 'keycloak'
      namespace: openshift-gitops
    spec:
      project: gitops-resources
      destination:
        server: https://kubernetes.default.svc
        namespace: tssc-keycloak
      source:
        repoURL: https://github.com/smatula/rhads-services-gitops
        path: ./components/keycloak
        targetRevision: tas-tpa-keycloak
        kustomize:
          patches:
            - patch: |
                - op: replace
                  path: /spec/host
                  # Keycloak hostname patch
                  value: "{{ index .metadata.annotations "KChost" }}"
              target:
                kind: Route
                name: keycloak
            - patch: |
                - op: replace
                  path: /spec/hostname/hostname
                  # Keycloak hostname patch
                  value: "{{ index .metadata.annotations "KChost" }}"
              target:
                kind: Keycloak
                name: keycloak
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
