apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tas-service
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-service-app: "true"
  template:
    metadata:
      name: 'tas'
      namespace: openshift-gitops
    spec:
      project: gitops-resources
      destination:
        server: https://kubernetes.default.svc
        namespace: trusted-artifact-signer
      source:
        repoURL: https://github.com/smatula/rhads-services-gitops
        path: ./components/tas
        targetRevision: tas-tpa-keycloak
        kustomize:
          patches:
            - patch: |
                - op: replace
                  path: /spec/fulcio/config/OIDCIssuers/0/Issuer
                  # Securesign Isuer patch
                  value: "{{ index .metadata.annotations "tasIssuer" }}"
              target:
                kind: Securesign
                name: trusted-artifact-signer
            - patch: |
                - op: replace
                  path: /spec/fulcio/config/OIDCIssuers/0/IssuerURL
                  # Securesign IssuerURL patch
                  value: "{{ index .metadata.annotations "tasIssuer" }}"
              target:
                kind: Securesign
                name: trusted-artifact-signer
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
